# .pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Using a recent tag, adjust if needed based on pre-commit checks
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 24.8.0 # Match version from requirements-dev.txt
    hooks:
    -   id: black
        language_version: python3.11 # Changed to 3.11
-   repo: https://github.com/pycqa/flake8
    rev: 7.1.0 # Match version from requirements-dev.txt
    hooks:
    -   id: flake8
        # Ignore E501 (line too long) and W503 (line break before binary operator)
        args: ['--ignore=E501,W503']
        # Optional: Add args for flake8 config if needed
        # args: ['--config=setup.cfg']
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2 # Match version from requirements-dev.txt
    hooks:
    -   id: isort
        name: isort (python)
        args: ["--profile", "black"] # Add black compatibility profile
# Optional but Recommended: Mypy for type checking
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0 # Match version from requirements-dev.txt
    hooks:
    -   id: mypy
        # Optional: Add args if needed, e.g., path to config
        # args: [--config-file=mypy.ini]
        # Important: Add necessary types-* packages to requirements-dev.txt
        # e.g., types-requests, types-PyYAML, types-beautifulsoup4
        additional_dependencies: [types-requests, types-PyYAML, types-beautifulsoup4, types-selenium]
