target_url: "https://developer.dell.com/apis/4008/versions/3.6/docs"
output_directory: "output"
log_file: "logs/wyrm.log"
log_level: "INFO" # DEBUG, INFO, WARNING, ERROR, CRITICAL

webdriver:
  browser: "edge" # "chrome", "firefox", "edge"
  headless: true

# Delays and Timeouts (in seconds)
delays:
  # Base delays (used in headless mode or if no overrides are set)
  navigation: 15       # Timeout for initial page navigation
  element_wait: 15     # Default timeout for waiting for generic elements (if used)
  sidebar_wait: 30     # Specific timeout for waiting for sidebar container
  expand_menu: 0.5     # Delay between clicking menu expanders
  post_expand_settle: 1.0 # Delay after expansion loop before parsing
  # post_click: 0.5      # (For Phase 3) Delay after clicking a sidebar item
  # content_wait: 10     # (For Phase 3) Timeout waiting for content pane markdown

  # --- Optional overrides for non-headless mode (--no-headless) ---
  navigation_noheadless: 30
  sidebar_wait_noheadless: 30
  expand_menu_noheadless: 0.7
  post_expand_settle_noheadless: 2.0
  post_click_noheadless: 0.7
  content_wait_noheadless: 15

# Other Behaviors
behavior:
  # Base behavior
  max_expand_attempts: 10 # Max loops to try expanding menus
  # skip_existing: true    # (For Phase 4) Skip files if they exist

  # --- Optional overrides for non-headless mode ---
  # max_expand_attempts_noheadless: 15

# Parallel Processing Settings
concurrency:
  # Maximum number of concurrent content extraction tasks
  max_concurrent_tasks: 3
  # Enable parallel processing (set to false to use sequential processing)
  enabled: true
  # Rate limiting: minimum delay between starting new tasks (seconds)
  task_start_delay: 0.5
  # Maximum retries for failed parallel tasks before falling back to sequential
  max_parallel_retries: 2

debug_settings:
  # Directory for debug outputs (structure.json, sidebar_debug.html)
  output_directory: "debug"
  # Default filename for the saved structure JSON
  save_structure_filename: "structure_debug.json"
  # Default filename for the saved sidebar HTML
  save_html_filename: "sidebar_debug.html"
  # Seconds to pause the browser at the end when running non-headless
  non_headless_pause_seconds: 10
